# Generated by Django 6.0.1 on 2026-01-31 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='menus/')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='MenuPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_positions/')),
                ('name', models.CharField(max_length=300)),
                ('price', models.PositiveIntegerField()),
                ('volume', models.PositiveIntegerField()),
                ('volume_type', models.CharField(choices=[('ml', 'Миллилитры'), ('gr', 'Граммы')], max_length=10)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.menu')),
            ],
        ),
        migrations.CreateModel(
            name='MenuIngridient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('menu_position', models.ManyToManyField(related_name='ingridients', to='core.menuposition')),
            ],
        ),
        migrations.CreateModel(
            name='MenuTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name=80)),
                ('menu', models.ManyToManyField(to='core.menu')),
            ],
        ),
    ]
