# Generated by Django 6.0 on 2026-02-06 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_menuposition_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuposition',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.menu'),
        ),
    ]
