# Generated by Django 6.0.2 on 2026-02-12 15:21

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_menuposition_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('instagram', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('building_number', models.CharField(max_length=8)),
                ('phone_number', models.CharField(max_length=30)),
                ('map_url', models.URLField()),
                ('start_time', models.TimeField(default=datetime.time(21, 21, 53, 343086))),
                ('end_time', models.TimeField(default=datetime.time(21, 21, 53, 343086))),
            ],
        ),
        migrations.AlterField(
            model_name='menuposition',
            name='image',
            field=models.ImageField(default=1, upload_to='menus_positions/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuposition',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='core.menu'),
        ),
        migrations.AlterField(
            model_name='menuposition',
            name='volume_type',
            field=models.CharField(choices=[('ml', 'Миллилитры'), ('gr', 'Грамм')], max_length=11),
        ),
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('restaurant_point', models.ManyToManyField(related_name='weekdays', to='core.restaurantpoint')),
            ],
        ),
    ]
