# Generated by Django 6.0.2 on 2026-02-12 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contacts_restaurantpoint_alter_menuposition_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantpoint',
            name='end_time',
            field=models.TimeField(default=datetime.time(23, 35, 25, 319414)),
        ),
        migrations.AlterField(
            model_name='restaurantpoint',
            name='start_time',
            field=models.TimeField(default=datetime.time(23, 35, 25, 319414)),
        ),
    ]
