# Generated by Django 6.0.2 on 2026-02-14 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_restaurantpoint_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantpoint',
            name='end_time',
            field=models.TimeField(default=datetime.time(19, 50, 20, 341528)),
        ),
        migrations.AlterField(
            model_name='restaurantpoint',
            name='start_time',
            field=models.TimeField(default=datetime.time(19, 50, 20, 341528)),
        ),
    ]
